### ISSUE TITLE
Inference setup and code for Grounding DINO

### ISSUE THREAD

**Issue by Amaia-CARDIEL** [shikras/d-cube#11]
Hello, 

Thank you for your work and the release of your DOD dataset. 

Do you plan to release your evaluation code regarding other baselines than owl (especially for Grounding DINO) ?
We tried to evaluate the model on your dataset and could not reproduce the same results than those in your paper. 
Could you please provide details on your inference setup for Grounding DINO ? 

Thanks in advance

**Comment by Charles-Xie** [comment]
Thanks for your interest in this work. We have released the eval code for more works: SPHINX, Grounding-DINO, and UNINEXT, as listed in this page: https://github.com/shikras/d-cube/tree/main/eval_sota.
The Grounding-DINO code is available here: https://github.com/shikras/d-cube/blob/main/eval_sota/groundingdino.py.
We also include a new trick to boost the performance. You can try it after checking the code.
You can also refer to the wonderful implementation in MM-Grounding-DINO: https://github.com/open-mmlab/mmdetection/tree/main/configs/mm_grounding_dino.

**Comment by Charles-Xie** [comment]
I'm closing this issue now. Please feel free to open it or open another if any further questions arise.
