### ISSUE TITLE
Training and Evaluation split for Group-wise RES

### ISSUE THREAD

**Issue by ShramanPramanick** [shikras/d-cube#4]
Hi, I could not find the split information of GRES. None of the json files mention this. Can you please clarify which images did you use for training and which for evaluation for GRES?

**Comment by Charles-Xie** [comment]
Hi,
Thanks for your interest in our work! We appreciate that very much.
For the GRES paper/task, we use the proposed dataset only for evaluation. This dataset contains no images for training and all images are for evaluation. 
I hope this would clarify your question, and please go on with the question if my answer is not clear.
:blush: :blush: :blush:

**Comment by Charles-Xie** [comment]
This issue is not active for some time so I'm closing it for now. Feel free to reopen it or open another one if any questions arises.
