### ISSUE TITLE
Some images have no associated annotations?

### ISSUE THREAD

**Issue by ImcwjHere** [shikras/d-cube#5]
```
images = pickle.load(open("images.pkl", "rb"))
count = 0
for image in images.items():
    anno_id = image[1]["anno_id"]
    if not len(anno_id):
        count += 1     
# Output: count = 2690
```

Are there 2690 images that don't have a corresponding anno_id?

**Comment by Charles-Xie** [comment]
Hi,
Thanks for your interest in our work! We appreciate that very much.
About your question, the answer is yes. There are some images that does not have a corresponding `anno_id`. These images contain no positive instances of the 422 categories annotated in our dataset, i.e., they are negative samples for all the categories.

**Comment by Charles-Xie** [comment]
I think this issue is resolved so I will close it now. Please feel free to reopen it if the question is not clarified or open another issue if you have any other question. We are very thankful for your attention to our work.

**Comment by hhaAndroid** [comment]
@Charles-Xie What are negative samples used for? Are they useful during evaluation?

**Comment by Charles-Xie** [comment]
> @Charles-Xie What are negative samples used for? Are they useful during evaluation?

Sorry for the late reply.
Negative samples are also used during evaluation. For a category, the ideal model should reject any predictions on the negative samples. This verifies an important aspect of detection models, i.e., rejecting negative samples and avoiding FP predictions.
