### ISSUE TITLE
I have not find the model proposed in paper "Advancing Referring Expression Segmentation Beyond Single Image"

### ISSUE THREAD

**Issue by MI-WENYU** [shikras/d-cube#6]
Thank you for opening up your dataset.  in your code, I have not find the model proposed in paper "Advancing Referring Expression Segmentation Beyond Single Image" . When do you plan to expose your model code?

**Comment by yixuan730** [comment]
Hello, thanks for your attention. Please contact wyx_chloe@zju.edu.cn if model code needed.

**Comment by yixuan730** [comment]
Hello, thanks for your attention. Please contact 2948819544@qq.com if model code needed.

**Comment by MI-WENYU** [comment]
Thank you for your reply.


| |
wenyu_mi
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/14/2023 15:19 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [shikras/d-cube] I have not find the model proposed in paper "Advancing Referring Expression Segmentation Beyond Single Image" (Issue #6) |

Hello, thanks for your attention. Please contact ***@***.*** if model code needed.

**Comment by Charles-Xie** [comment]
This issue is not active for some time so I'm closing it for now. Feel free to reopen it or open another one if any questions arises.
