### ISSUE TITLE
the 'is_negative' meaning?

### ISSUE THREAD

**Issue by peiliu0408** [shikras/d-cube#8]
in sentences.pkl file, each 'sentence' contain a field 'is_negative', what that meaning?

<img width="571" alt="截屏2024-01-03 16 01 34" src="https://github.com/shikras/d-cube/assets/18061950/c1f03d80-68d0-4394-ae58-938a0a8edca3">

**Comment by Charles-Xie** [comment]
Hi, thanks for your interest!
For each 'sentence' in the sentences.pkl file, the field 'is_negative' denotes whether this expression is an absence expression (e.g., "dog **without** leash") or not. More specifically, a 'sentence' with 'is_negative' as True means it is an absence expression and False means it is a presence expression.

We also explain this in the [documentation of d-cube](https://github.com/shikras/d-cube/blob/main/doc.md#sent), but we called absence expression as "anti-expression" at that time. We call it absence expression now.

If you have further questions, please feel free to mention them.

**Comment by Charles-Xie** [comment]
This issue is not active for some time so I'm closing it for now. Feel free to reopen it or open another one if any questions arises.
