### ISSUE TITLE
Grounding DINO

### ISSUE THREAD

**Issue by Zesheng666** [shikras/d-cube#9]
你好啊，能不能公开一下Grounding DINO  方法在该数据集的代码，我这边验证老是有BUG

**Comment by Charles-Xie** [comment]
Thanks for your interest in this work. We have released the eval code for more works. The grounding-dino code is available here: https://github.com/shikras/d-cube/blob/main/eval_sota/groundingdino.py.

**Comment by Charles-Xie** [comment]
I'm closing this issue now. Please feel free to open it or open another if any further questions arise.

**Comment by Zesheng666** [comment]
Hello author, I encountered a very slow inference phenomenon when testing with G-DINO: Intra: 4.0, 4.3, 3.7, in Inter mode: the inference speed is extremely slow, about 2 minutes per sheet, and there have been no results for two days. Do you know what the reason is? Looking forward to your reply very much

**Comment by Zesheng666** [comment]
作者你好，有个问题想要请教你一下，我在用G_DINO(official)测试D_3数据集时候出现intri 时候结果为

model

full

pre

abense


gdinot-1.8m

0.224

0.220

0.236


gdinot-coco-ft

0.024

0.023

0.025


gdino_swint（offical）

0.032

0.030

0.040


&nbsp;

&nbsp;

&nbsp;




远远低于论文里面的正常值，你能帮我分析一下原因吗？还有在inter模式下，推理很慢，一天时间才能完成大概1/10，你遇到类似的情况吗，望回复，谢谢










&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Mar 5, 2024 05:49 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [shikras/d-cube] Grounding DINO (Issue #9)

&nbsp;



 
Closed #9 as completed.
